### ISSUE TITLE
Cannot find "Full Stack Cloud Application"

### ISSUE THREAD

**Issue by Auggie9010** [SAP-samples/teched2020-IIS360#1]
## Where I had this trouble
Exercises>Getting Started - Setting up your Development Environment>Creating the Development Space>Enter a name for your development space and select application profile Full Stack Cloud Application.

![image](https://user-images.githubusercontent.com/57590680/101781371-1072cb80-3b3b-11eb-8a62-0aa37ee71a91.png)

## The content of trouble
I cannot find `Full Stack Cloud Application`.
![image](https://user-images.githubusercontent.com/57590680/101781477-339d7b00-3b3b-11eb-9e12-6be55841ec5a.png)

(Maybe is this the privilege of the participant of the workshop?)

## Note
I did not register this workshop.
I tried this exercise from the session catalog.

![image](https://user-images.githubusercontent.com/57590680/101781734-8aa35000-3b3b-11eb-94cc-79777454c160.png)

I created SCP trial account and subscribed BAS before start this exercise.

**Comment by Auggie9010** [comment]
I chose `SAP Cloud Business Application` instead and could reach exercise 7.

**Comment by c-kobo** [comment]
The dev spaces names  shown in the exercises were already available in the dedicated TechEd SAP Business Application Studio instance and are expected to roll out to production end of this week. Until then, you can use SAP Cloud Business Application in your own trial account in order to complete the exercises.

**Comment by donal-tobin-sap** [comment]
The naming of the dev space `SAP Cloud Business Application` has not been updated yet on the Trial (and productive) systems, and unfortunately I do not know when it will be updated.
